### ISSUE TITLE
wrong expression cause dead loop

### ISSUE THREAD

**Issue by troycheng** [wysaid/simple-arithmetic#1]
an invalid Expression:    9+(2/7)2*.22+    caused dead loop
it generates bellow expressions:
@0 =    2/7,
@1 = @02*.22,
@2 =   9+@1,
@3 =    @2+,
when met @1, parse function get next step @02, the code using sscanf("02", "%d", index) to get next step, here is 2, and then go back to @2, and a dead loop happen

**Comment by wysaid** [comment]
Get. I'll fix that.

**Comment by wysaid** [comment]
Done.

**Comment by troycheng** [comment]
confirmed & thanks
