### ISSUE TITLE
wrong status when sub node is invalid 

### ISSUE THREAD

**Issue by troycheng** [wysaid/simple-arithmetic#2]
for this case:

` s="..5*4*3";`
` ArithmeticExpression expression(s);`
` if (expression) { print ... }`

because ..5 is not a valid equation, the code shouldn't go into if block, however it does. 
I traced and found it caused by these code:

`ArithmeticNode *leftNode, *rightNode;`
`leftNode = parseSimpleNode(left);`
`rightNode = parseSimpleNode(right);`
`opNode->addChildNode(leftNode);`
`opNode->addChildNode(rightNode);`

parseSimpleNode(..5) return nullptr, and addChildNode did a check and not really add it, thus, the status of m_node is like:

> [
>     [*, 4],
>     [3]
> ]

isValid() function consider it is true, and then value() computes result and returns 0...seems some more efforts to be done here. 

To fix, just check whether leftNode or rightNode is null can work but I'm not sure it obeys your original design.

the output of code:

> ..5\*4\*3
> @0 =  ..5\*4,
> @1 =   @0\*3,
> Invalid node: ..5
> ..5\*4\*3 = 0  //this line was output only when expression(s) is true, in this case it should not appear

**Comment by wysaid** [comment]
I see, I'll fix that.

**Comment by wysaid** [comment]
Done. Please checkout the commit above. 😬

**Comment by troycheng** [comment]
confirmed，thanks for your effort
